### ISSUE TITLE
[PE-D][Tester C] Invalid deadline error message does not match actual error

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W12-3/tp#137]
![image.png](https://raw.githubusercontent.com/jinyang628/ped/main/files/4cbedf16-79fa-499a-a9fc-b256807c00c6.png)

Expected error message: The deadline should not be before the current date and time

Actual error message: Deadline should be in valid DateTime format: MMM dd yyyy HHmm

I believe that the format of my deadline is correct as shown in the screenshot above and that the error message is misleading.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: jinyang628/ped#6

**Comment by evanyan13** [comment]
Closes w #172
