### ISSUE TITLE
[PE-D][Tester C] Inability to sort company names by descending order

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W12-3/tp#140]
I can only sort company names by ascending order. Suppose I have a very large list and I want to find a company name that starts with the letter ‘Z’. I forgot how to spell the company name exactly so I cannot use the find command (since the find command is not useful in searching for applications with partially matching keywords as stated in the UG). 

The only way I can find my desired entry is to sort by company name (in ascending order) and scroll through possibly thousands of entries. This is undesirable for the user. In my opinion, this suggests that the feature is not complete.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: jinyang628/ped#7

**Comment by peiran18** [comment]
Sort UG: ascending only
