### ISSUE TITLE
[PE-D][Tester D] Unclear date format

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W12-3/tp#146]
I was trying to add an interview for a company with this command:
"interview add 1 t/technical d/dec 12 2030 1400 a/home"

![Screenshot 2023-11-03 at 4.35.52 PM.png](https://raw.githubusercontent.com/wasjoe1/ped/main/files/c9545f04-8d34-4e47-8ee2-925c01318a74.png)

the return error message correctly identified that the issue was to do with the datetime parameter. However i was slightly confused with why it was wrong. I went to the UG to check what format it was supposed to be yet i was filling in the right MMM dd yyyy HHmm format. Then only by trial and error, I realised that the month name has to be typed with a capital letter for the first letter. It would be of freat help if this could be rectified as I had quite a bit of difficulty figuring out why I couldn't add my interview time slot :)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: wasjoe1/ped#5

**Comment by evanyan13** [comment]
Closes w #172
