### ISSUE TITLE
[PE-D][Tester D] Being able to add multiple interviews at the same time slot

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W12-3/tp#158]
I was adding interviews and had not realise that i had clashes with my different types of interview for the same company. I think having an warning message to tell me i have clashing interviews would be great :)

![Screenshot 2023-11-03 at 5.02.57 PM.png](https://raw.githubusercontent.com/wasjoe1/ped/main/files/b7adcc23-ed50-4d4d-ba20-e5992ea0d789.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: wasjoe1/ped#9

**Comment by peiran18** [comment]
Can include interviews at the same time slots

**Comment by evanyan13** [comment]
Thank you for the feedback. But as discussed by the team, we think it is more logical to allow user to add interviews with the timeslot as it does not necessarily mean the user must attend the interview just by recording it
