### ISSUE TITLE
[PE-D][Tester D] sorting by company name

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W12-3/tp#166]
I wanted to sort the list of companies by the name but the UG did not state so

![Screenshot 2023-11-04 at 12.00.45 AM.png](https://raw.githubusercontent.com/wasjoe1/ped/main/files/df6625a1-99b5-4d25-893b-00cd8db2b3ee.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: wasjoe1/ped#13

**Comment by evanyan13** [comment]
![Screenshot 2023-11-06 at 3 43 00 PM](https://github.com/AY2324S1-CS2103T-W12-3/tp/assets/103996156/1f7fdd3a-9124-4d20-89d0-da27bcc7a880)

As stated in this line in the UG, please refer to the "Structure of a job application" for the list of valid prefixes.
